DRINKS =	espresso.cc \
		 	house_blend.cc \
		 	dark_roast.cc

DECORATORS =	condiment_decorator.cc \
				mocha.cc \
				soy.cc \
			 	whip.cc

SRCS =	main.cc \
	  	beverage.cc \
	  	$(DRINKS) \
	  	$(DECORATORS)

all:
	g++ $(SRCS) -o beverages.o
	./beverages.o
	