DRINKS = espresso.cpp \
		 house_blend.cpp \
		 dark_roast.cpp

DECORATORS = condiment_decorator.cpp \
			 mocha.cpp \
			 soy.cpp \
			 whip.cpp

SRCS = main.cpp \
	   beverage.cpp \
	   $(DRINKS) \
	   $(DECORATORS)

all:
	g++ $(SRCS) -o beverages.o
	./beverages.o
	