PIZZE = ../pizze/ny_style_cheese_pizza.cc \
		../pizze/ny_style_clam_pizza.cc \
		../pizze/ny_style_pepperoni_pizza.cc \
		../pizze/ny_style_veggie_pizza.cc

SRCS =	main.cc \
		$(PIZZE) \
		../pizze/pizza.cc \
		pizza_store.cc \
		ny_style_pizza_store.cc

all:
	g++ $(SRCS) -o abstract_method.o -std=c++11
	./abstract_method.o
	