PIZZE = pizze/pizza.cc \
		pizze/cheese_pizza.cc

SRCS =	$(PIZZE) \
		main.cc \
		ny_pizza_ingredient_factory.cc \
		pizza_store.cc \
		ny_style_pizza_store.cc

all:
	g++ $(SRCS) -o abstract_factory.o -std=c++11
	./abstract_factory.o
	